defaults: &defaults
  # Logic config
  registration_is_open: true
  event_is_over: false
  last_day_to_apply: <%= Date.new(2018, 1, 22) %>
  auto_late_waitlist: false

  # Content config
  name: BrickHack
  logo_asset: brickhack.png
  agreement_pdf_asset: BrickHack_ReleaseAgreement.pdf
  email_from: '"BrickHack" <hello@brickhack.io>'
  default_page_title: BrickHack 4 - Jan 27-28, 2018

  disclaimer: |
    Applicants must be 18 years of age by January 27th.
  thanks_for_applying: |
    Thanks for applying! You will be notified of your acceptance via email in January.
  bus_captain_notes: |
    * Only students on this list may board the bus. **No exceptions**- this is to ensure everyone goes through the application process & has signed RIT's waivers.
    * If any emergencies arise, call our travel director, **Velizar Demirev**, at **(413) 221-2420**.
    * If you have any other questions, please feel free to email [travel@brickhack.io](mailto:travel@brickhack.io)

development:
  <<: *defaults

test: &test
  <<: *defaults
  last_day_to_apply: <%= 2.months.from_now %>

production:
  <<: *defaults

staging:
  <<: *defaults
