defaults: &defaults
  # Logic config
  registration_is_open: false
  event_is_over: true
  last_day_to_apply: <%= Date.new(2018, 1, 22) %>
  auto_late_waitlist: true

  # Content config
  name: BrickHack
  logo_asset: brickhack.png
  agreement_pdf_asset: BrickHack_ReleaseAgreement.pdf
  email_from: '"BrickHack" <hello@brickhack.io>'
  default_page_title: BrickHack 4 - Jan 27-28, 2018

  disclaimer: |
    Applicants must be 18 years of age by January 27th.
  thanks_for_applying: |
    Thanks for applying! You will be notified of your acceptance via email in January.

development:
  <<: *defaults

test: &test
  <<: *defaults
  last_day_to_apply: <%= 2.months.from_now %>

production:
  <<: *defaults

staging:
  <<: *defaults
